[package]
name = "mist-signer-rust"
version = "0.1.0"
authors = ["eddy <792130043@qq.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.0"

